#-------------------------------
# General Site Settings
# baseurl: "/yeste-studio-website/" # the subpath of your site, e.g. /blog
# baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://yeste.studio/" # the base hostname & protocol for your site, e.g. http://example.com
# url: "https://javier-sy.github.io"
#-------------------------------

# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 9
paginate_path: "/blog/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
  - scope:
      path: '_posts'
    values:
      permalink: /blog/:slug

include:
  - _pages

exclude:
  - .idea/

sass:
  sass_dir: _sass
  style: compressed

# Necesario para el plugin de jekyll->github pages
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font