#-------------------------------
# General Site Settings
# baseurl: "/yeste-studio-website/" # the subpath of your site, e.g. /blog
# baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://yeste.studio" # the base hostname & protocol for your site, e.g. http://example.com
# url: "https://javier-sy.github.io"
#-------------------------------

# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-sitemap

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
  - scope:
      type: news
    values:
      layout: news
  - scope:
      type: letters
    values:
      layout: letter

include:
  - _pages

exclude:
  - .idea/

# Collections
collections:
  works:
    output: true
    permalink: /works/:title/
  phd_music:
    output: true
    permalink: /phd/materials/:title/
  events:
    output: false
  news:
    output: true
    permalink: /news/:year/:slug/
  letters:
    output: true
    permalink: /news/letters/:slug/

sass:
  sass_dir: _sass
  style: compressed
  silence_deprecations:
    - import
